from __future__ import annotations

import argparse
import hashlib
import platform
import re
import sys
import zipfile
from email.parser import Parser
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the Windows CPython 3.10 hash lock from downloaded wheels."
    )
    parser.add_argument("wheelhouse", type=Path)
    parser.add_argument("output_path", type=Path)
    parser.add_argument(
        "--target",
        choices=["py310-win", "py311-linux", "py312-linux"],
        default="py310-win",
    )
    parser.add_argument("--profile", choices=["dev", "runtime"], default="dev")
    args = parser.parse_args()

    expected_minor = {"py310-win": 10, "py311-linux": 11, "py312-linux": 12}[
        args.target
    ]
    expected_os = "Windows" if args.target == "py310-win" else "Linux"
    if (
        sys.version_info[:2] != (3, expected_minor)
        or platform.python_implementation() != "CPython"
    ):
        raise RuntimeError(f"Target requires CPython 3.{expected_minor}")
    if platform.system() != expected_os or platform.machine().lower() not in {
        "amd64",
        "x86_64",
    }:
        raise RuntimeError(f"Target requires {expected_os} x86_64")

    from packaging.tags import sys_tags
    from packaging.utils import parse_wheel_filename

    supported = set(sys_tags())
    for wheel in args.wheelhouse.glob("*.whl"):
        if not supported.intersection(parse_wheel_filename(wheel.name)[3]):
            raise ValueError(f"Wheel is incompatible with target: {wheel.name}")

    records = collect_wheel_records(args.wheelhouse)
    args.output_path.write_text(
        render_lock(records, args.target, args.profile), encoding="ascii", newline="\n"
    )
    print(f"Generated {args.output_path} with {len(records)} locked wheels")
    return 0


def collect_wheel_records(wheelhouse: Path) -> list[dict[str, object]]:
    if not wheelhouse.is_dir():
        raise ValueError("wheelhouse must be an existing directory")
    unexpected = sorted(
        path.name for path in wheelhouse.iterdir() if path.suffix != ".whl"
    )
    if unexpected:
        raise ValueError(f"wheelhouse contains non-wheel files: {unexpected!r}")

    records: list[dict[str, object]] = []
    seen: set[str] = set()
    for wheel_path in sorted(
        wheelhouse.glob("*.whl"), key=lambda path: path.name.lower()
    ):
        name, version = read_wheel_identity(wheel_path)
        canonical_name = canonicalize_name(name)
        if canonical_name in seen:
            raise ValueError(
                f"wheelhouse contains duplicate distribution {canonical_name!r}"
            )
        seen.add(canonical_name)
        records.append(
            {
                "name": canonical_name,
                "version": version,
                "sha256": hashlib.sha256(wheel_path.read_bytes()).hexdigest(),
            }
        )
    if not records:
        raise ValueError("wheelhouse must contain at least one wheel")
    return sorted(records, key=lambda record: str(record["name"]))


def read_wheel_identity(wheel_path: Path) -> tuple[str, str]:
    with zipfile.ZipFile(wheel_path) as archive:
        metadata_files = [
            name
            for name in archive.namelist()
            if name.count("/") == 1 and name.endswith(".dist-info/METADATA")
        ]
        if len(metadata_files) != 1:
            raise ValueError(
                f"wheel must contain exactly one top-level METADATA: {wheel_path.name}"
            )
        metadata = Parser().parsestr(archive.read(metadata_files[0]).decode("utf-8"))
    name = metadata.get("Name")
    version = metadata.get("Version")
    if not name or not version:
        raise ValueError(
            f"wheel metadata is missing Name or Version: {wheel_path.name}"
        )
    return name, version


def render_lock(
    records: list[dict[str, object]], target: str = "py310-win", profile: str = "dev"
) -> str:
    lines = [
        "# Generated by scripts/generate-python-lock.ps1; do not edit manually.",
        "# Target: CPython 3.10, Windows AMD64, wheel-only installation.",
        "# Source roots: backend/requirements-py310-win.in",
        "",
    ]
    if target != "py310-win":
        minor = 12 if target == "py312-linux" else 11
        lines = [
            "# Generated by scripts/generate-linux-lock.sh; do not edit manually.",
            f"# Target: CPython 3.{minor}, Linux x86_64, wheel-only; profile: {profile}.",
            f"# Source roots: backend/requirements-{target}-{profile}.in",
            "",
        ]
    for record in records:
        lines.extend(
            [
                f"{record['name']}=={record['version']} \\",
                f"    --hash=sha256:{record['sha256']}",
            ]
        )
    return "\n".join(lines) + "\n"


def canonicalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


if __name__ == "__main__":
    raise SystemExit(main())
