from typing import Final

DOE_PRODUCT_FACTOR_LIMIT: Final = 10
FACTORIAL_AUTHORING_FACTOR_LIMIT: Final = DOE_PRODUCT_FACTOR_LIMIT
GENERAL_FACTORIAL_AUTHORING_FACTOR_LIMIT: Final = DOE_PRODUCT_FACTOR_LIMIT
LATIN_HYPERCUBE_FACTOR_LIMIT: Final = DOE_PRODUCT_FACTOR_LIMIT
BAYESIAN_STUDY_FACTOR_LIMIT: Final = DOE_PRODUCT_FACTOR_LIMIT
RESPONSE_SURFACE_CCD_FACTOR_LIMIT: Final = 5

FACTORIAL_RUN_LIMIT: Final = 256
GENERAL_FACTORIAL_RUN_LIMIT: Final = 256
